export const bowlStyles = {
  bowlContainer: {
    border: "black solid 2px",
    maxHeight: "200px",
    width: "800px",
    fontSize: "1.3rem",
    marginTop: "15px",
    boxShadow: "1px 1px 8px 1px rgba(0, 0, 0, 0.4)",
    backgroundColor: "#fff",
    borderRadius: "10px",
    padding: "15px",
  },
  bowlList: {
    listStyleType: "none",
    display: "flex",
    flexDirection: "column",
    flexWrap: "wrap",
    gap: "10px",
    fontWeight: "bolder",
    maxHeight: "200px",
    width: "800px",
  },
  ingredient: {
    display: "flex",
    maxWidth: "auto",
    height: "30px",
    border: "solid 2px gray",
    fontFamily: "Mukta",
    letterSpacing: "2px",
    boxShadow: "1px 1px 2px 1px rgba(0, 0, 0, 0.6)",
    backgroundColor: "#fff",
    borderRadius: "10px",
    paddingLeft: "10px",
    paddingTop: "2px",
  },
  ingredientName: {
    marginRight: "5px",
    marginTop: "-5px",
    maxWidth: "150px",
    wordWrap: "break-word",
  },
};
