export const cuisines = [
  "Any",
  "American",
  "Asian",
  "British",
  "Caribbean",
  "Central Europe",
  "Chinese",
  "Eastern Europe",
  "French",
  "Indian",
  "Italian",
  "Japanese",
  "Kosher",
  "Mediterranean",
  "Mexican",
  "Middle Eastern",
  "Nordic",
  "South American",
  "South East Asian",
];

export const meals = ["Any", "Breakfast", "Lunch", "Dinner", "Snack"];

export const health = [
  "Any",
  "Alcohol-cocktail",
  "Alcohol-free",
  "Celery-free",
  "Crustacean-free",
  "Dairy-free",
  "DASH",
  "Egg-free",
  "Fish-free",
  "Fodmap-free",
  "Gluten-free",
  "Immuno-supportive",
  "Keto-friendly",
  "Kidney-friendly",
  "Kosher",
  "Low-fat-abs",
  "Low-potassium",
  "Low-sugar",
  "Lupine-free",
  "Mollusk-free",
  "Mustard-free",
  "No-oil-added",
  "Paleo",
  "Peanut-free",
  "Pescatarian",
  "Pork-free",
  "Red-meat-free",
  "Sesame-free",
  "Shellfish-free",
  "Soy-free",
  "Sugar-conscious",
  "Sulfite-free",
  "Tree-nut-free",
  "Vegan",
  "Vegetarian",
  "Wheat-free",
];
