export const ingredientsStyles = {
  ingredientsContainer: {
    display: "flex",
    flexDirection: "column",
    maxWidth: "250px",
    marginLeft: "25px",
    top: "10px",
    left: "40px",
    fontFamily: "Mukta",
    letterSpacing: "2px",
    boxShadow: "1px 1px 8px 1px rgba(0, 0, 0, 0.4)",
    backgroundColor: "#fff",
    padding: "15px",
    borderRadius: "10px",
  },
  formContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  ingredientInput: {
    marginTop: "10px",
    height: "30px",
    borderRadius: "10px",
    boxShadow: "2px 2px 1px 0 rgba(0, 0, 0, 0.2)",
    fontSize: "1.2rem",
    padding: "5px",
    fontWeight: "bolder",
  },
  cuisineInput: {
    height: "40px",
    borderRadius: "10px",
    boxShadow: "2px 2px 1px 0 rgba(0, 0, 0, 0.2)",
    fontSize: "1.2rem",
    padding: "5px",
    fontWeight: "bolder",
  },
  mealInput: {
    height: "40px",
    borderRadius: "10px",
    boxShadow: "2px 2px 1px 0 rgba(0, 0, 0, 0.2)",
    fontSize: "1.2rem",
    padding: "5px",
    fontWeight: "bolder",
  },
  healthType: {
    height: "40px",
    borderRadius: "10px",
    boxShadow: "2px 2px 1px 0 rgba(0, 0, 0, 0.2)",
    fontSize: "1.2rem",
    padding: "5px",
    fontWeight: "bolder",
  },
  submitInput: {
    height: "40px",
    borderRadius: "10px",
    border: "none",
    boxShadow: "2px 2px 1px 0 rgba(0, 0, 0, 0.2)",
    fontSize: "1.2rem",
    padding: "5px",
    fontWeight: "bolder",
  },
};
