export const ingredientsStyles = {
  ingredientsContainer: {
    display: "flex",
    flexDirection: "column",
    maxWidth: "200px",
    position: "relative",
    top: "60px",
    left: "50px",
    fontFamily: "mukta",
    letterSpacing: "2px",
  },
  formContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  ingredientInput: {
    marginTop: "10px",
    height: "30px",
    borderRadius: "10px",
    boxShadow: "2px 2px 1px 0 rgba(0, 0, 0, 0.2)",
    fontSize: "1.2rem",
    padding: "5px",
    fontWeight: "bolder",
  },
  cuisineInput: {
    height: "40px",
    borderRadius: "10px",
    boxShadow: "2px 2px 1px 0 rgba(0, 0, 0, 0.2)",
    fontSize: "1.2rem",
    padding: "5px",
    fontWeight: "bolder",
  },
  mealInput: {
    height: "40px",
    borderRadius: "10px",
    boxShadow: "2px 2px 1px 0 rgba(0, 0, 0, 0.2)",
    fontSize: "1.2rem",
    padding: "5px",
    fontWeight: "bolder",
  },
  healthType: {
    height: "40px",
    borderRadius: "10px",
    boxShadow: "2px 2px 1px 0 rgba(0, 0, 0, 0.2)",
    fontSize: "1.2rem",
    padding: "5px",
    fontWeight: "bolder",
  },
  submitInput: {
    height: "40px",
    borderRadius: "10px",
    border: "none",
    boxShadow: "2px 2px 1px 0 rgba(0, 0, 0, 0.2)",
    fontSize: "1.2rem",
    padding: "5px",
    fontWeight: "bolder",
  },
};
